### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by ru0** [AlsidOfficial/WSUSpendu#4]
hello,Is a great pleasure read this project,i am very interested to  know how wsus works.I wonder whether windows update from internet would find any different.

**Comment by Aorimn** [comment]
Hi,
WSUS from Internet is delivered by Microsoft, a "trusted" provider since you're using Microsoft products, over an HTTPS connection.
WSUSpendu is about stealthily injecting an update in the provider's database that will be executed on clients. If Microsoft wants to execute something on clients, it wouldn't bother to use this and simply provide an update (that's actually what they do for all updates).

**Comment by Aorimn** [comment]
I'm closing this issue as the question seems to have been answered. Feel free to continue the discussion afterward on this subject.

**Comment by ru0** [comment]
老铁，我不是这个意思啊 -_#
